FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt requirements-web.txt ./
RUN pip install -r requirements.txt
RUN pip install -r requirements-web.txt

# Copy application code
COPY . .

# Expose port
EXPOSE 8501

# Run the application
CMD ["streamlit", "run", "app/frontend/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]